//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable=false)]
public partial class Person {
    
    private string displayNameField;
    
    private string accountIdField;
    
    private string accountTypeField;
    
    /// <remarks/>
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string AccountId {
        get {
            return this.accountIdField;
        }
        set {
            this.accountIdField = value;
        }
    }
    
    /// <remarks/>
    public string AccountType {
        get {
            return this.accountTypeField;
        }
        set {
            this.accountTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable=false)]
public partial class BDCAssociatedEntity {
    
    private BDCEntity[] bDCEntityField;
    
    private string entityNamespaceField;
    
    private string entityNameField;
    
    private string systemInstanceNameField;
    
    private string associationNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BDCEntity")]
    public BDCEntity[] BDCEntity {
        get {
            return this.bDCEntityField;
        }
        set {
            this.bDCEntityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string EntityNamespace {
        get {
            return this.entityNamespaceField;
        }
        set {
            this.entityNamespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string EntityName {
        get {
            return this.entityNameField;
        }
        set {
            this.entityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string SystemInstanceName {
        get {
            return this.systemInstanceNameField;
        }
        set {
            this.systemInstanceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string AssociationName {
        get {
            return this.associationNameField;
        }
        set {
            this.associationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable=false)]
public partial class BDCEntity {
    
    private string entityDisplayNameField;
    
    private string entityInstanceReferenceField;
    
    private string entityId1Field;
    
    private string entityId2Field;
    
    private string entityId3Field;
    
    private string entityId4Field;
    
    private string entityId5Field;
    
    /// <remarks/>
    public string EntityDisplayName {
        get {
            return this.entityDisplayNameField;
        }
        set {
            this.entityDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public string EntityInstanceReference {
        get {
            return this.entityInstanceReferenceField;
        }
        set {
            this.entityInstanceReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string EntityId1 {
        get {
            return this.entityId1Field;
        }
        set {
            this.entityId1Field = value;
        }
    }
    
    /// <remarks/>
    public string EntityId2 {
        get {
            return this.entityId2Field;
        }
        set {
            this.entityId2Field = value;
        }
    }
    
    /// <remarks/>
    public string EntityId3 {
        get {
            return this.entityId3Field;
        }
        set {
            this.entityId3Field = value;
        }
    }
    
    /// <remarks/>
    public string EntityId4 {
        get {
            return this.entityId4Field;
        }
        set {
            this.entityId4Field = value;
        }
    }
    
    /// <remarks/>
    public string EntityId5 {
        get {
            return this.entityId5Field;
        }
        set {
            this.entityId5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable=false)]
public partial class Terms {
    
    private TermInfo[] termInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TermInfo")]
    public TermInfo[] TermInfo {
        get {
            return this.termInfoField;
        }
        set {
            this.termInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls", IsNullable=false)]
public partial class TermInfo {
    
    private string termNameField;
    
    private string termIdField;
    
    /// <remarks/>
    public string TermName {
        get {
            return this.termNameField;
        }
        set {
            this.termNameField = value;
        }
    }
    
    /// <remarks/>
    public string TermId {
        get {
            return this.termIdField;
        }
        set {
            this.termIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum NGEN {
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group4 {
    
    private ProjectMgrReasonForDenial projectMgrReasonForDenialField;
    
    /// <remarks/>
    public ProjectMgrReasonForDenial ProjectMgrReasonForDenial {
        get {
            return this.projectMgrReasonForDenialField;
        }
        set {
            this.projectMgrReasonForDenialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class ProjectMgrReasonForDenial {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class userid {
    
    private Person personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
    public Person Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MgrName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Waybright, Marc")]
    WaybrightMarc,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum Segment {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Consulting &amp; Intelligence")]
    ConsultingampIntelligence,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group10 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group11 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group12 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group13 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group14 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class group15 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CardType {
    
    /// <remarks/>
    CAC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum LastName {
    
    /// <remarks/>
    Merkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=true)]
public partial class LostDate {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MgrEmail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("marc.waybright@hpe.com")]
    marcwaybrighthpecom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class myFields {
    
    private DefaultValues defaultValuesField;
    
    private FormOption formOptionField;
    
    private BadgeInfo badgeInfoField;
    
    private BadgeReturn badgeReturnField;
    
    private BadgeEntry badgeEntryField;
    
    private BadgeLost badgeLostField;
    
    private ProjectMgrApprovalSection projectMgrApprovalSectionField;
    
    private OptionSection optionSectionField;
    
    private FormOptionHeader formOptionHeaderField;
    
    private SubmisionErrorText submisionErrorTextField;
    
    private group10 group10Field;
    
    private BadgeApprovedError badgeApprovedErrorField;
    
    private OtherSegmentError otherSegmentErrorField;
    
    private string langField;
    
    /// <remarks/>
    public DefaultValues DefaultValues {
        get {
            return this.defaultValuesField;
        }
        set {
            this.defaultValuesField = value;
        }
    }
    
    /// <remarks/>
    public FormOption FormOption {
        get {
            return this.formOptionField;
        }
        set {
            this.formOptionField = value;
        }
    }
    
    /// <remarks/>
    public BadgeInfo BadgeInfo {
        get {
            return this.badgeInfoField;
        }
        set {
            this.badgeInfoField = value;
        }
    }
    
    /// <remarks/>
    public BadgeReturn BadgeReturn {
        get {
            return this.badgeReturnField;
        }
        set {
            this.badgeReturnField = value;
        }
    }
    
    /// <remarks/>
    public BadgeEntry BadgeEntry {
        get {
            return this.badgeEntryField;
        }
        set {
            this.badgeEntryField = value;
        }
    }
    
    /// <remarks/>
    public BadgeLost BadgeLost {
        get {
            return this.badgeLostField;
        }
        set {
            this.badgeLostField = value;
        }
    }
    
    /// <remarks/>
    public ProjectMgrApprovalSection ProjectMgrApprovalSection {
        get {
            return this.projectMgrApprovalSectionField;
        }
        set {
            this.projectMgrApprovalSectionField = value;
        }
    }
    
    /// <remarks/>
    public OptionSection OptionSection {
        get {
            return this.optionSectionField;
        }
        set {
            this.optionSectionField = value;
        }
    }
    
    /// <remarks/>
    public FormOptionHeader FormOptionHeader {
        get {
            return this.formOptionHeaderField;
        }
        set {
            this.formOptionHeaderField = value;
        }
    }
    
    /// <remarks/>
    public SubmisionErrorText SubmisionErrorText {
        get {
            return this.submisionErrorTextField;
        }
        set {
            this.submisionErrorTextField = value;
        }
    }
    
    /// <remarks/>
    public group10 group10 {
        get {
            return this.group10Field;
        }
        set {
            this.group10Field = value;
        }
    }
    
    /// <remarks/>
    public BadgeApprovedError BadgeApprovedError {
        get {
            return this.badgeApprovedErrorField;
        }
        set {
            this.badgeApprovedErrorField = value;
        }
    }
    
    /// <remarks/>
    public OtherSegmentError OtherSegmentError {
        get {
            return this.otherSegmentErrorField;
        }
        set {
            this.otherSegmentErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class DefaultValues {
    
    private ManagerIDAccount managerIDAccountField;
    
    private CurrentUser currentUserField;
    
    private UserIDAccountName userIDAccountNameField;
    
    private FormSubmitted formSubmittedField;
    
    private UserIDisCurrentID userIDisCurrentIDField;
    
    private ProjectMgrAccountID projectMgrAccountIDField;
    
    private sbyte maxIDField;
    
    private BadgeHolderAcctID badgeHolderAcctIDField;
    
    private SubstringAfterAcctID substringAfterAcctIDField;
    
    private InvalidFields invalidFieldsField;
    
    private MissingFields missingFieldsField;
    
    private MissingOtherSegment missingOtherSegmentField;
    
    private ProjMgrApproved projMgrApprovedField;
    
    private System.DateTime approvedDateField;
    
    private MissingBadgeFields missingBadgeFieldsField;
    
    private MissingIssueDate missingIssueDateField;
    
    private MissingExpirationDate missingExpirationDateField;
    
    private MissingAgency missingAgencyField;
    
    private BadgeCompleted badgeCompletedField;
    
    private System.DateTime badgeCompletedDateField;
    
    private FormStatus formStatusField;
    
    private DataViewSubmit dataViewSubmitField;
    
    private NGEN nGENField;
    
    /// <remarks/>
    public ManagerIDAccount ManagerIDAccount {
        get {
            return this.managerIDAccountField;
        }
        set {
            this.managerIDAccountField = value;
        }
    }
    
    /// <remarks/>
    public CurrentUser CurrentUser {
        get {
            return this.currentUserField;
        }
        set {
            this.currentUserField = value;
        }
    }
    
    /// <remarks/>
    public UserIDAccountName UserIDAccountName {
        get {
            return this.userIDAccountNameField;
        }
        set {
            this.userIDAccountNameField = value;
        }
    }
    
    /// <remarks/>
    public FormSubmitted FormSubmitted {
        get {
            return this.formSubmittedField;
        }
        set {
            this.formSubmittedField = value;
        }
    }
    
    /// <remarks/>
    public UserIDisCurrentID UserIDisCurrentID {
        get {
            return this.userIDisCurrentIDField;
        }
        set {
            this.userIDisCurrentIDField = value;
        }
    }
    
    /// <remarks/>
    public ProjectMgrAccountID ProjectMgrAccountID {
        get {
            return this.projectMgrAccountIDField;
        }
        set {
            this.projectMgrAccountIDField = value;
        }
    }
    
    /// <remarks/>
    public sbyte MaxID {
        get {
            return this.maxIDField;
        }
        set {
            this.maxIDField = value;
        }
    }
    
    /// <remarks/>
    public BadgeHolderAcctID BadgeHolderAcctID {
        get {
            return this.badgeHolderAcctIDField;
        }
        set {
            this.badgeHolderAcctIDField = value;
        }
    }
    
    /// <remarks/>
    public SubstringAfterAcctID SubstringAfterAcctID {
        get {
            return this.substringAfterAcctIDField;
        }
        set {
            this.substringAfterAcctIDField = value;
        }
    }
    
    /// <remarks/>
    public InvalidFields InvalidFields {
        get {
            return this.invalidFieldsField;
        }
        set {
            this.invalidFieldsField = value;
        }
    }
    
    /// <remarks/>
    public MissingFields MissingFields {
        get {
            return this.missingFieldsField;
        }
        set {
            this.missingFieldsField = value;
        }
    }
    
    /// <remarks/>
    public MissingOtherSegment MissingOtherSegment {
        get {
            return this.missingOtherSegmentField;
        }
        set {
            this.missingOtherSegmentField = value;
        }
    }
    
    /// <remarks/>
    public ProjMgrApproved ProjMgrApproved {
        get {
            return this.projMgrApprovedField;
        }
        set {
            this.projMgrApprovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ApprovedDate {
        get {
            return this.approvedDateField;
        }
        set {
            this.approvedDateField = value;
        }
    }
    
    /// <remarks/>
    public MissingBadgeFields MissingBadgeFields {
        get {
            return this.missingBadgeFieldsField;
        }
        set {
            this.missingBadgeFieldsField = value;
        }
    }
    
    /// <remarks/>
    public MissingIssueDate MissingIssueDate {
        get {
            return this.missingIssueDateField;
        }
        set {
            this.missingIssueDateField = value;
        }
    }
    
    /// <remarks/>
    public MissingExpirationDate MissingExpirationDate {
        get {
            return this.missingExpirationDateField;
        }
        set {
            this.missingExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    public MissingAgency MissingAgency {
        get {
            return this.missingAgencyField;
        }
        set {
            this.missingAgencyField = value;
        }
    }
    
    /// <remarks/>
    public BadgeCompleted BadgeCompleted {
        get {
            return this.badgeCompletedField;
        }
        set {
            this.badgeCompletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BadgeCompletedDate {
        get {
            return this.badgeCompletedDateField;
        }
        set {
            this.badgeCompletedDateField = value;
        }
    }
    
    /// <remarks/>
    public FormStatus FormStatus {
        get {
            return this.formStatusField;
        }
        set {
            this.formStatusField = value;
        }
    }
    
    /// <remarks/>
    public DataViewSubmit DataViewSubmit {
        get {
            return this.dataViewSubmitField;
        }
        set {
            this.dataViewSubmitField = value;
        }
    }
    
    /// <remarks/>
    public NGEN NGEN {
        get {
            return this.nGENField;
        }
        set {
            this.nGENField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ManagerIDAccount {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("americas\\waybrigm")]
    americaswaybrigm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CurrentUser {
    
    /// <remarks/>
    curtbrad,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum UserIDAccountName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("americas\\merkel")]
    americasmerkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum FormSubmitted {
    
    /// <remarks/>
    Yes,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum UserIDisCurrentID {
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectMgrAccountID {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("americas\\merkel")]
    americasmerkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum BadgeHolderAcctID {
    
    /// <remarks/>
    i,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum SubstringAfterAcctID {
    
    /// <remarks/>
    merkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum InvalidFields {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingFields {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingOtherSegment {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjMgrApproved {
    
    /// <remarks/>
    Yes,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingBadgeFields {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingIssueDate {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingExpirationDate {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MissingAgency {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum BadgeCompleted {
    
    /// <remarks/>
    Yes,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum FormStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Card Active")]
    CardActive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum DataViewSubmit {
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum FormOption {
    
    /// <remarks/>
    New,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class BadgeInfo {
    
    private userid useridField;
    
    private CardStatus cardStatusField;
    
    private LastName lastNameField;
    
    private FirstName firstNameField;
    
    private MiddleName middleNameField;
    
    private UserDisplayName userDisplayNameField;
    
    private int employeeIDField;
    
    private CompanyEmail companyEmailField;
    
    private PersonalEmail personalEmailField;
    
    private OtherEmail otherEmailField;
    
    private Telephone telephoneField;
    
    private MgrName mgrNameField;
    
    private MgrEmail mgrEmailField;
    
    private MgrDisplayName mgrDisplayNameField;
    
    private MgrTelephone mgrTelephoneField;
    
    private CardType cardTypeField;
    
    private Segment segmentField;
    
    private OtherSegment otherSegmentField;
    
    private ProjectName projectNameField;
    
    private ProjectNumber projectNumberField;
    
    private OtherProjectNumber otherProjectNumberField;
    
    private ProjectManagerEmail projectManagerEmailField;
    
    private ProjectManagerTelephone projectManagerTelephoneField;
    
    private System.DateTime projectExpirationDateField;
    
    private UserIDValidation1 userIDValidation1Field;
    
    private CompanyName companyNameField;
    
    private CompanyPhone companyPhoneField;
    
    private ManagerID managerIDField;
    
    private ProjectManagerID projectManagerIDField;
    
    private ProjectManagerName projectManagerNameField;
    
    private ProjectManagerDisplayName projectManagerDisplayNameField;
    
    private LastNameErrorText lastNameErrorTextField;
    
    private FirstNameErrorText firstNameErrorTextField;
    
    private group11 group11Field;
    
    private group12 group12Field;
    
    private group13 group13Field;
    
    private group14 group14Field;
    
    private group15 group15Field;
    
    private HolderMGR holderMGRField;
    
    private RequestRemarks requestRemarksField;
    
    /// <remarks/>
    public userid userid {
        get {
            return this.useridField;
        }
        set {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    public CardStatus CardStatus {
        get {
            return this.cardStatusField;
        }
        set {
            this.cardStatusField = value;
        }
    }
    
    /// <remarks/>
    public LastName LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public FirstName FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public MiddleName MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public UserDisplayName UserDisplayName {
        get {
            return this.userDisplayNameField;
        }
        set {
            this.userDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public int EmployeeID {
        get {
            return this.employeeIDField;
        }
        set {
            this.employeeIDField = value;
        }
    }
    
    /// <remarks/>
    public CompanyEmail CompanyEmail {
        get {
            return this.companyEmailField;
        }
        set {
            this.companyEmailField = value;
        }
    }
    
    /// <remarks/>
    public PersonalEmail PersonalEmail {
        get {
            return this.personalEmailField;
        }
        set {
            this.personalEmailField = value;
        }
    }
    
    /// <remarks/>
    public OtherEmail OtherEmail {
        get {
            return this.otherEmailField;
        }
        set {
            this.otherEmailField = value;
        }
    }
    
    /// <remarks/>
    public Telephone Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public MgrName MgrName {
        get {
            return this.mgrNameField;
        }
        set {
            this.mgrNameField = value;
        }
    }
    
    /// <remarks/>
    public MgrEmail MgrEmail {
        get {
            return this.mgrEmailField;
        }
        set {
            this.mgrEmailField = value;
        }
    }
    
    /// <remarks/>
    public MgrDisplayName MgrDisplayName {
        get {
            return this.mgrDisplayNameField;
        }
        set {
            this.mgrDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public MgrTelephone MgrTelephone {
        get {
            return this.mgrTelephoneField;
        }
        set {
            this.mgrTelephoneField = value;
        }
    }
    
    /// <remarks/>
    public CardType CardType {
        get {
            return this.cardTypeField;
        }
        set {
            this.cardTypeField = value;
        }
    }
    
    /// <remarks/>
    public Segment Segment {
        get {
            return this.segmentField;
        }
        set {
            this.segmentField = value;
        }
    }
    
    /// <remarks/>
    public OtherSegment OtherSegment {
        get {
            return this.otherSegmentField;
        }
        set {
            this.otherSegmentField = value;
        }
    }
    
    /// <remarks/>
    public ProjectName ProjectName {
        get {
            return this.projectNameField;
        }
        set {
            this.projectNameField = value;
        }
    }
    
    /// <remarks/>
    public ProjectNumber ProjectNumber {
        get {
            return this.projectNumberField;
        }
        set {
            this.projectNumberField = value;
        }
    }
    
    /// <remarks/>
    public OtherProjectNumber OtherProjectNumber {
        get {
            return this.otherProjectNumberField;
        }
        set {
            this.otherProjectNumberField = value;
        }
    }
    
    /// <remarks/>
    public ProjectManagerEmail ProjectManagerEmail {
        get {
            return this.projectManagerEmailField;
        }
        set {
            this.projectManagerEmailField = value;
        }
    }
    
    /// <remarks/>
    public ProjectManagerTelephone ProjectManagerTelephone {
        get {
            return this.projectManagerTelephoneField;
        }
        set {
            this.projectManagerTelephoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ProjectExpirationDate {
        get {
            return this.projectExpirationDateField;
        }
        set {
            this.projectExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    public UserIDValidation1 UserIDValidation1 {
        get {
            return this.userIDValidation1Field;
        }
        set {
            this.userIDValidation1Field = value;
        }
    }
    
    /// <remarks/>
    public CompanyName CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public CompanyPhone CompanyPhone {
        get {
            return this.companyPhoneField;
        }
        set {
            this.companyPhoneField = value;
        }
    }
    
    /// <remarks/>
    public ManagerID ManagerID {
        get {
            return this.managerIDField;
        }
        set {
            this.managerIDField = value;
        }
    }
    
    /// <remarks/>
    public ProjectManagerID ProjectManagerID {
        get {
            return this.projectManagerIDField;
        }
        set {
            this.projectManagerIDField = value;
        }
    }
    
    /// <remarks/>
    public ProjectManagerName ProjectManagerName {
        get {
            return this.projectManagerNameField;
        }
        set {
            this.projectManagerNameField = value;
        }
    }
    
    /// <remarks/>
    public ProjectManagerDisplayName ProjectManagerDisplayName {
        get {
            return this.projectManagerDisplayNameField;
        }
        set {
            this.projectManagerDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public LastNameErrorText LastNameErrorText {
        get {
            return this.lastNameErrorTextField;
        }
        set {
            this.lastNameErrorTextField = value;
        }
    }
    
    /// <remarks/>
    public FirstNameErrorText FirstNameErrorText {
        get {
            return this.firstNameErrorTextField;
        }
        set {
            this.firstNameErrorTextField = value;
        }
    }
    
    /// <remarks/>
    public group11 group11 {
        get {
            return this.group11Field;
        }
        set {
            this.group11Field = value;
        }
    }
    
    /// <remarks/>
    public group12 group12 {
        get {
            return this.group12Field;
        }
        set {
            this.group12Field = value;
        }
    }
    
    /// <remarks/>
    public group13 group13 {
        get {
            return this.group13Field;
        }
        set {
            this.group13Field = value;
        }
    }
    
    /// <remarks/>
    public group14 group14 {
        get {
            return this.group14Field;
        }
        set {
            this.group14Field = value;
        }
    }
    
    /// <remarks/>
    public group15 group15 {
        get {
            return this.group15Field;
        }
        set {
            this.group15Field = value;
        }
    }
    
    /// <remarks/>
    public HolderMGR HolderMGR {
        get {
            return this.holderMGRField;
        }
        set {
            this.holderMGRField = value;
        }
    }
    
    /// <remarks/>
    public RequestRemarks RequestRemarks {
        get {
            return this.requestRemarksField;
        }
        set {
            this.requestRemarksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CardStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Card Active")]
    CardActive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum FirstName {
    
    /// <remarks/>
    Matt,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class MiddleName {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum UserDisplayName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(" Matt Merkel")]
    MattMerkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CompanyEmail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("matthew.merkel7@hpe.com")]
    matthewmerkel7hpecom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum PersonalEmail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("matthew.merkel@outlook.com")]
    matthewmerkeloutlookcom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum OtherEmail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("matthew.merkel@outlook.com")]
    matthewmerkeloutlookcom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum Telephone {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("+1 703 713 8072")]
    Item17037138072,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MgrDisplayName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(" Marc Waybright")]
    MarcWaybright,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum MgrTelephone {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("+1 540 4311505")]
    Item15404311505,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum OtherSegment {
    
    /// <remarks/>
    adfadf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectName {
    
    /// <remarks/>
    FDA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectNumber {
    
    /// <remarks/>
    FDA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum OtherProjectNumber {
    
    /// <remarks/>
    adf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectManagerEmail {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("matthew.merkel7@hpe.com")]
    matthewmerkel7hpecom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectManagerTelephone {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("+1 703 713 8072")]
    Item17037138072,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class UserIDValidation1 {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CompanyName {
    
    /// <remarks/>
    HPE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum CompanyPhone {
    
    /// <remarks/>
    adsfadf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class ManagerID {
    
    private Person personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
    public Person Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class ProjectManagerID {
    
    private Person personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
    public Person Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectManagerName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Merkel, Matt")]
    MerkelMatt,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectManagerDisplayName {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(" Matt Merkel")]
    MattMerkel,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class LastNameErrorText {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class FirstNameErrorText {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class HolderMGR {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum RequestRemarks {
    
    /// <remarks/>
    adfadf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class BadgeReturn {
    
    private ReturnDate returnDateField;
    
    private ReturnReason returnReasonField;
    
    private CHReturnedTo cHReturnedToField;
    
    private CHReturnedBy cHReturnedByField;
    
    private PMReturnReason pMReturnReasonField;
    
    private PMReturnedTo pMReturnedToField;
    
    private PMReturnedBy pMReturnedByField;
    
    private PMReturnDate pMReturnDateField;
    
    private CHReturnAuthority cHReturnAuthorityField;
    
    private PMReturnAuthority pMReturnAuthorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ReturnDate ReturnDate {
        get {
            return this.returnDateField;
        }
        set {
            this.returnDateField = value;
        }
    }
    
    /// <remarks/>
    public ReturnReason ReturnReason {
        get {
            return this.returnReasonField;
        }
        set {
            this.returnReasonField = value;
        }
    }
    
    /// <remarks/>
    public CHReturnedTo CHReturnedTo {
        get {
            return this.cHReturnedToField;
        }
        set {
            this.cHReturnedToField = value;
        }
    }
    
    /// <remarks/>
    public CHReturnedBy CHReturnedBy {
        get {
            return this.cHReturnedByField;
        }
        set {
            this.cHReturnedByField = value;
        }
    }
    
    /// <remarks/>
    public PMReturnReason PMReturnReason {
        get {
            return this.pMReturnReasonField;
        }
        set {
            this.pMReturnReasonField = value;
        }
    }
    
    /// <remarks/>
    public PMReturnedTo PMReturnedTo {
        get {
            return this.pMReturnedToField;
        }
        set {
            this.pMReturnedToField = value;
        }
    }
    
    /// <remarks/>
    public PMReturnedBy PMReturnedBy {
        get {
            return this.pMReturnedByField;
        }
        set {
            this.pMReturnedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PMReturnDate PMReturnDate {
        get {
            return this.pMReturnDateField;
        }
        set {
            this.pMReturnDateField = value;
        }
    }
    
    /// <remarks/>
    public CHReturnAuthority CHReturnAuthority {
        get {
            return this.cHReturnAuthorityField;
        }
        set {
            this.cHReturnAuthorityField = value;
        }
    }
    
    /// <remarks/>
    public PMReturnAuthority PMReturnAuthority {
        get {
            return this.pMReturnAuthorityField;
        }
        set {
            this.pMReturnAuthorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=true)]
public partial class ReturnDate {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class ReturnReason {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class CHReturnedTo {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class CHReturnedBy {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class PMReturnReason {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class PMReturnedTo {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class PMReturnedBy {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=true)]
public partial class PMReturnDate {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class CHReturnAuthority {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class PMReturnAuthority {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class BadgeEntry {
    
    private short badgeNumberField;
    
    private System.DateTime badgeIssueDateField;
    
    private System.DateTime badgeExpirationDateField;
    
    private AgencyIssuedBy agencyIssuedByField;
    
    /// <remarks/>
    public short BadgeNumber {
        get {
            return this.badgeNumberField;
        }
        set {
            this.badgeNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BadgeIssueDate {
        get {
            return this.badgeIssueDateField;
        }
        set {
            this.badgeIssueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BadgeExpirationDate {
        get {
            return this.badgeExpirationDateField;
        }
        set {
            this.badgeExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    public AgencyIssuedBy AgencyIssuedBy {
        get {
            return this.agencyIssuedByField;
        }
        set {
            this.agencyIssuedByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum AgencyIssuedBy {
    
    /// <remarks/>
    daf,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class BadgeLost {
    
    private LostorStolen lostorStolenField;
    
    private LostDate lostDateField;
    
    private LostReportDate lostReportDateField;
    
    private LostReportedTo lostReportedToField;
    
    private LossExplanation lossExplanationField;
    
    /// <remarks/>
    public LostorStolen LostorStolen {
        get {
            return this.lostorStolenField;
        }
        set {
            this.lostorStolenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LostDate LostDate {
        get {
            return this.lostDateField;
        }
        set {
            this.lostDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LostReportDate LostReportDate {
        get {
            return this.lostReportDateField;
        }
        set {
            this.lostReportDateField = value;
        }
    }
    
    /// <remarks/>
    public LostReportedTo LostReportedTo {
        get {
            return this.lostReportedToField;
        }
        set {
            this.lostReportedToField = value;
        }
    }
    
    /// <remarks/>
    public LossExplanation LossExplanation {
        get {
            return this.lossExplanationField;
        }
        set {
            this.lossExplanationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class LostorStolen {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=true)]
public partial class LostReportDate {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class LostReportedTo {
    
    private Person personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2007/PartnerControls")]
    public Person Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class LossExplanation {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class ProjectMgrApprovalSection {
    
    private group4 group4Field;
    
    private ProjectMgrApproval projectMgrApprovalField;
    
    /// <remarks/>
    public group4 group4 {
        get {
            return this.group4Field;
        }
        set {
            this.group4Field = value;
        }
    }
    
    /// <remarks/>
    public ProjectMgrApproval ProjectMgrApproval {
        get {
            return this.projectMgrApprovalField;
        }
        set {
            this.projectMgrApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public enum ProjectMgrApproval {
    
    /// <remarks/>
    Approve,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class OptionSection {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class FormOptionHeader {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class SubmisionErrorText {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class BadgeApprovedError {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/office/infopath/2003/myXSD/2015-09-16T14:27:45", IsNullable=false)]
public partial class OtherSegmentError {
}
